name: Deploy User Service

on:
  push:
    branches:
      - main
    paths:
      - 'users/**' # ทำงานเมื่อโฟลเดอร์ users มีการเปลี่ยนแปลง

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: user-service
          region: asia-southeast1
          source: ./users
          flags: '--allow-unauthenticated'