name: Deploy API Gateway

on:
  push:
    branches:
      - main
    paths:
      - "api-gateway/**"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: api-gateway
          region: asia-southeast1
          source: ./api-gateway
          # 🎯 แก้ไขบรรทัดนี้: ใส่ URL จริง และเพิ่ม ORDERS_SERVICE_URL เข้าไป (คั่นด้วยลูกน้ำ)
          flags: "--allow-unauthenticated --set-env-vars=USER_SERVICE_URL=https://user-service-879165280409.asia-southeast1.run.app,ORDERS_SERVICE_URL=https://order-service-879165280409.asia-southeast1.run.app"
