name: Deploy Microservices

on:
  push:
    branches:
      - main # (หรือเปลี่ยนเป็น deploy ถ้าคุณต้องการใช้ branch อื่น)
    paths:
      - 'systems/**'  # ทำงานเมื่อมีการแก้ไฟล์ใน jobs

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      # 🚀 สเตป Deploy Jobs Service
      - name: Deploy System Service
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: system-service
          region: asia-southeast1
          source: ./systems
          flags: '--allow-unauthenticated'